config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'static_pages#index'
  get '/about', to: 'static_pages#about'
  resources :users do
    resources :posts, module: :users, only: %i[create destroy]
    member do
      get 'groups', to: 'users#groups', as: :groups
    end
  end
  resources :groups do
    resources :posts, module: :groups, only: %i[create destroy]
    resources :members, module: :groups, only: %i[index show create destroy] do
      delete 'remove_member', to: 'members#remove_member', as: :remove_member
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  MUSIC = 'music'.freeze
  FILM = 'film'.freeze
  SOCIAL = 'social'.freeze
  OTHER = 'other'.freeze

  GROUP_TYPE = [OTHER, MUSIC, FILM, SOCIAL].freeze
  enum group_type: GROUP_TYPE

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts, as: :postable, dependent: :destroy

  validates :group_name,  presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 120 }
  validates :group_type, presence: true, inclusion: { in: GROUP_TYPE }

  mount_uploader :image, ImageUploader
  paginates_per 6

  def user_moderator?(user)
    user_groups.moderators.for_user(user).present?
  end
end

# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  description :string
#  group_name  :string
#  group_type  :integer          default("other")
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/groups/members_controller.rb
class Groups::MembersController < ApplicationController
  GROUP_USERS_PREVIEW_AMOUNT = 4
  before_action :authenticate_user!
  before_action :set_group
  before_action :set_group_members

  def index
    @users = User.by_joining_the_group(@group).page(params[:page])
  end

  def show; end

  def create
    @group.user_groups.create(user_id: current_user.id)
    render 'groups/members/follow_btn'
  end

  def destroy
    @group.user_groups.find_by(user_id: current_user.id).destroy
    render 'groups/members/follow_btn'
  end

  def remove_member
    if @group.user_moderator?(current_user) || current_user.admin?
      @group.user_groups.find_by(user_id: params[:member_id]).destroy
      flash[:warning] = 'User has been removed from group!'
      redirect_to group_members_path
    else
      flash[:warning] = 'Access denied'
      render 'groups/user_members'
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_group_members
    @group_members = User.by_joining_the_group(@group).limit(GROUP_USERS_PREVIEW_AMOUNT)
  end
end

app/controllers/groups/posts_controller.rb
class Groups::PostsController < PostsController
  private

  def set_postable
    @postable = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  GROUP_USERS_PREVIEW_AMOUNT = 4
  before_action :set_group, only: %i[show edit update destroy]
  before_action :set_group_members, only: %i[show]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @groups = Group.ordered_by_created_at.page(params[:page])
  end

  def show
    @post = @group.posts.new
    @posts = @group.posts.with_creator.ordered_by_created_at
  end

  def new
    @group = Group.new
  end

  def edit
    unless @group.user_moderator?(current_user) || current_user.admin?
      flash[:warning] = 'Access denied'
      render :show
    end
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.user_groups.create(user_id: current_user.id, moderator: true)
      flash[:success] = "group \"#{@group.group_name}\" created"
      redirect_to @group
    else
      flash[:warning] = 'Invalid parameters'
      render :new
    end
  end

  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    if @group.user_moderator?(current_user) || current_user.admin?
      if @group.update(group_params)
        flash[:success] = "group \"#{@group.group_name}\"  updated"
        redirect_to @group
      else
        flash[:warning] = 'Invalid parameters for editing!'
        render :edit
      end
    else
      flash[:warning] = 'Access denied'
      render :show
    end
  end

  def destroy
    @group.destroy!
    flash[:warning] = "Group \"#{@group.group_name}\" has been deleted"
    redirect_to groups_path
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def set_group_members
    @group_members = User.by_joining_the_group(@group).limit(GROUP_USERS_PREVIEW_AMOUNT)
  end

  def group_params
    params.require(:group).permit(:group_name,
                                  :description,
                                  :group_type,
                                  :image)
  end
end

app/views/groups/members/_follow_unfollow_buttons.html.slim
- if @group.users.exists?(id: current_user.id)
  = link_to 'unfollow', group_member_path(group_id: @group.id, id: current_user.id), id: 'follow', class: 'btn btn-user', method: :delete, remote: true
- else
  = link_to 'follow', group_members_path(group_id: @group.id), id: 'follow', class: 'btn btn-user', method: :post, remote: true

app/views/groups/members/_user.html.slim
.row.centered-form.center-blockm.m-3
  .container
    .card-user
      .user
        .row
          .col-lg-5
            .profile-image
              - if user.image?
                = image_tag(user.image.index.url, alt: 'Image', class: 'profile-image')
              - else
                = image_tag('default_avatar.png', alt: 'Image', class: 'profile-image')
          .col-lg-7
            h4.m-t-0.m-b-0
              strong = user.full_name
            span = user.email
            .row
              = link_to 'Show', user, class: 'btn btn-user-show'
              - if @group.user_moderator?(current_user) || current_user&.admin?
                 = link_to 'Delete User', group_member_remove_member_path(group_id: @group.id, member_id: user.id),
                    method: :delete, data: { confirm: 'Are you sure you want to remove user from this group?' },
                                      class: 'btn btn-user-show'

app/views/groups/members/_user_block_members.html.slim
.col-md-6
  .card-body.p-2
    .profile-img-group.d-flex.justify-content-center
      - if user.image?
        = image_tag(user.image.index.url, alt: 'Image', class: 'profile-image')
      - else
        = image_tag('default_avatar.png', alt: 'Image', class: 'profile-image')
    .group-name
      .d-flex.justify-content-center
        strong = user.full_name

app/views/groups/members/_user_members.html.slim
#members-block.row
  - @group_members.each do |user|
    = render 'groups/members/user_block_members', user: user

app/views/groups/members/follow_btn.js.erb
$('#follow').replaceWith('<%= j render "follow_unfollow_buttons"%>');
$('#members-block').replaceWith('<%= j render "user_members"%>');

app/views/groups/members/index.html.slim
- provide(:title, "#{@group.group_name} Members")
.jumbotron
  h1 #{@group.group_name} Members
  .row
    - @users.each do |member|
      = render 'groups/members/user', user: member
  = paginate @users, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm pagination-centered"