config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'static_pages#index'
  get '/about', to: 'static_pages#about'
  resources :users do
    resources :posts, module: :users, only: %i[create destroy]
    member do
      get 'groups', to: 'users#groups', as: :groups
    end
  end
  resources :groups do
    resources :posts, module: :groups, only: %i[create destroy]
    resources :members, module: :groups, only: %i[index show create destroy] do
      delete 'remove_member', to: 'members#remove_member', as: :remove_member
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  MUSIC = 'music'.freeze
  FILM = 'film'.freeze
  SOCIAL = 'social'.freeze
  OTHER = 'other'.freeze

  GROUP_TYPE = [OTHER, MUSIC, FILM, SOCIAL].freeze
  enum group_type: GROUP_TYPE

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts, as: :postable, dependent: :destroy

  validates :group_name,  presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 120 }
  validates :group_type, presence: true, inclusion: { in: GROUP_TYPE }

  mount_uploader :image, ImageUploader
  paginates_per 6

  def user_moderator?(user)
    user_groups.moderators.for_user(user).present?
  end
end

# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  description :string
#  group_name  :string
#  group_type  :integer          default("other")
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/groups/members_controller.rb
class Groups::MembersController < ApplicationController
  GROUP_USERS_PREVIEW_AMOUNT = 4
  before_action :authenticate_user!
  before_action :set_group
  before_action :set_group_members

  def index
    @users = User.by_joining_the_group(@group).page(params[:page])
  end

  def show; end

  def create
    @group.user_groups.create(user_id: current_user.id)
    render 'groups/members/follow_btn'
  end

  def destroy
    @group.user_groups.find_by(user_id: current_user.id).destroy
    render 'groups/members/follow_btn'
  end

  def remove_member
    if @group.user_moderator?(current_user) || current_user.admin?
      @group.user_groups.find_by(user_id: params[:member_id]).destroy
      flash[:warning] = 'User has been removed from group!'
      redirect_to group_members_path
    else
      flash[:warning] = 'Access denied'
      render 'groups/user_members'
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_group_members
    @group_members = User.by_joining_the_group(@group).limit(GROUP_USERS_PREVIEW_AMOUNT)
  end
end

app/controllers/groups/posts_controller.rb
class Groups::PostsController < PostsController
  private

  def set_postable
    @postable = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  GROUP_USERS_PREVIEW_AMOUNT = 4
  before_action :set_group, only: %i[show edit update destroy]
  before_action :set_group_members, only: %i[show]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @groups = Group.ordered_by_created_at.page(params[:page])
  end

  def show
    @post = @group.posts.new
    @posts = @group.posts.with_creator.ordered_by_created_at
  end

  def new
    @group = Group.new
  end

  def edit
    unless @group.user_moderator?(current_user) || current_user.admin?
      flash[:warning] = 'Access denied'
      render :show
    end
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.user_groups.create(user_id: current_user.id, moderator: true)
      flash[:success] = "group \"#{@group.group_name}\" created"
      redirect_to @group
    else
      flash[:warning] = 'Invalid parameters'
      render :new
    end
  end

  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    if @group.user_moderator?(current_user) || current_user.admin?
      if @group.update(group_params)
        flash[:success] = "group \"#{@group.group_name}\"  updated"
        redirect_to @group
      else
        flash[:warning] = 'Invalid parameters for editing!'
        render :edit
      end
    else
      flash[:warning] = 'Access denied'
      render :show
    end
  end

  def destroy
    @group.destroy!
    flash[:warning] = "Group \"#{@group.group_name}\" has been deleted"
    redirect_to groups_path
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def set_group_members
    @group_members = User.by_joining_the_group(@group).limit(GROUP_USERS_PREVIEW_AMOUNT)
  end

  def group_params
    params.require(:group).permit(:group_name,
                                  :description,
                                  :group_type,
                                  :image)
  end
end

app/views/groups/_form.html.slim
- provide(:title, 'Edit')
.d-flex.justify-content-center
  = simple_form_for @group do |f|
    .container
      .d-flex.justify-content-center
        .card
          .card-header
            h3
             | Edit Group
          .card-body
            .input-group.form-group
              .input-group-prepend
                span.input-group-text
                  i.fas.fa-users-cog
              .field
                = f.input :group_name, placeholder: 'group name', label: false
            .input-group.form-group
              .input-group-prepend
                span.input-group-text
                  i.fas.fa-users-cog
              .field
                = f.input :description, prepend: 'With textarea', as: :text, label: false,
                                        input_html: { style: 'width: 104%'}
            .input-group.form-group
              .input-group-prepend
              .field
                = f.file_field :image, style: 'max-width: 256px'
                = f.error :image
            .input-group.form-group
              .input-group-prepend
              .field
                = f.input :group_type, collection: Group::GROUP_TYPE
      .actions
        .row
          = f.submit 'Submit', class: 'btn btn-edit'
          = link_to 'Back', groups_path, class: 'btn btn-edit'
          = link_to 'Delete',  @group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-edit'

app/views/groups/_group.html.slim
.col-md-4
  .card.mb-4
    .profile-image.prof-img.d-flex.justify-content-center
      - if group.image?
        = image_tag(group.image.show.url, alt: 'Image', class: 'profile-image')
      - else
        = image_tag('default_group.png', alt: 'Image', class: 'post-img')
    .card-body
      .d-flex.justify-content-center
        strong = group.group_name
      .d-flex.justify-content-center
        span = group.group_type
      p.card-text
        = group.description
      .d-flex.justify-content-center.align-items-center
        = link_to 'Show', group, class: 'btn btn-sm btn-outline-secondary'

app/views/groups/_user.html.slim
.col-md-6
  .card-body.p-2
    .profile-img-group.d-flex.justify-content-center
      - if user.image?
        = image_tag(user.image.index.url, alt: 'Image', class: 'profile-image')
      - else
        = image_tag("default_avatar.png", alt: 'Image', class: 'profile-image')
    .group-name
      .d-flex.justify-content-center
        strong = user.full_name

app/views/groups/edit.html.slim
.jumbotron
  = render 'form', object: @group

app/views/groups/follow.js.erb
$('#follow').replaceWith('<%= j render "groups/follow_unfollow_buttons"%>');
$('#members-block').replaceWith('<%= j render "groups/user_members"%>');

app/views/groups/index.html.slim
- provide(:title, 'All group')
.jumbotron
  h1
    | All Groups
  h2
    | new group
    = link_to new_group_path
     button.btn-outline-light.btn-custom
       i.fas.fa-plus
  .row
    = render @groups
  = paginate @groups, theme: 'twitter-bootstrap-4', pagination_class: 'pagination-sm pagination-centered'

app/views/groups/members.html.slim
- provide(:title, "#{@group.group_name} Members")
.jumbotron
  h1 #{@group.group_name} Members
  .row
    - @users.each do |member|
      = render 'users/user', user: member
  = paginate @users, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm pagination-centered"

app/views/groups/new.html.slim
- provide(:title, 'New Group')
.jumbotron
  = render 'form'

app/views/groups/show.html.slim
- provide(:title, @group.group_name)
.jumbotron.jumbotron2
  .main-body
    .row.gutters-sm
      .col-md-4.mb-3
        .card
          .card-body
            .d-flex.flex-column.align-items-center.text-center
              .profile-image
                - if @group.image?
                  = image_tag(@group.image.show.url, alt: 'Image', class: 'profile-image')
                - else
                  = image_tag('default_group.png', alt: 'Image', class: 'post-img')
              .mt-3
                h4
                  strong = @group.group_name
                h2
                  span = @group.group_type

              .mb-2.mt-1[style='min-height: 100px;']
                = @group.description
            .row
              = link_to 'Back', groups_path, class: 'btn btn-user'
              - if @group.user_moderator?(current_user) || current_user&.admin?
                = link_to 'Edit Group', edit_group_path(@group), class: 'btn btn-user'
              - if current_user
                = render 'groups/members/follow_unfollow_buttons'

        .card.mt-3.p-2[style='min-height: 339px;']
          = link_to group_members_path(group_id: @group.id), class: 'link-user-show' do
            h2.link-user-show.mb-2.mt-2
              | Members
          end
          = render 'groups/members/user_members'
      .col-md-8
        .card[style='min-height: 802px;']
          = render 'posts/form', { postable: @group }
          = render partial: 'posts/post', collection: @posts, as: :post