config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'static_pages#index'
  get '/about', to: 'static_pages#about'
  resources :users do
    resources :posts, module: :users, only: %i[create destroy]
    member do
      get 'groups', to: 'users#groups', as: :groups
    end
  end
  resources :groups do
    resources :posts, module: :groups, only: %i[create destroy]
    resources :members, module: :groups, only: %i[index show create destroy] do
      delete 'remove_member', to: 'members#remove_member', as: :remove_member
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  SOCIALS = {
    facebook: 'Facebook',
    google_oauth2: 'Google'
  }.freeze

  ADMIN = 'admin'.freeze
  SIMPLE = 'simple'.freeze

  ROLES = [ADMIN, SIMPLE].freeze
  enum role: ROLES

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
  has_many :posts, as: :postable, dependent: :destroy
  has_many :created_posts, class_name: 'Post', foreign_key: 'creator_id', dependent: :destroy, inverse_of: 'creator'

  validates :first_name,
            :last_name, presence: true, length: { maximum: 50 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true, length: { maximum: 255 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  scope :by_joining_the_group, lambda { |group|
    joins(:user_groups).where(user_groups: { group_id: group.id }).order('user_groups.updated_at DESC')
  }

  mount_uploader :image, ImageUploader
  paginates_per 10

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.from_omniauth(auth) # rubocop:disable Metrics/MethodLength
    name_split = auth.info.name.split
    user = User.find_by(email: auth.info.email)
    user ||= User.create(
      provider: auth.provider,
      uid: auth.uid,
      last_name: name_split[1],
      first_name: name_split[0],
      email: auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(254)      not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string(50)       not null
#  image                  :string
#  last_name              :string(50)       not null
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer          default("simple")
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/users/posts_controller.rb
class Users::PostsController < PostsController
  private

  def set_postable
    @postable = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user, only: %i[show edit update destroy groups]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @users = User.ordered_by_created_at.page(params[:page])
  end

  def show
    @post = @user.posts.new
    @posts = @user.posts.with_creator.ordered_by_created_at
  end

  def edit
    authorize @user
  end

  def destroy
    authorize @user
    if @user.destroy
      redirect_to users_path
      flash[:danger] = "User profile \"#{@user.full_name}\" has been deleted"
    else
      flash.now[:warning] = 'Delete failed!'
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      flash[:success] = "User profile \"#{@user.full_name}\" updated"
      redirect_to @user
    else
      flash.now[:warning] = 'Invalid parameters for editing!'
      render :edit
    end
  end

  def groups
    @groups = @user.groups.page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :image)
  end

  def user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.slim
- provide(:title, 'Edit')
.d-flex.justify-content-center
  = simple_form_for @user do |f|
    .container
      .d-flex.justify-content-center
        .card
          .card-header
            h3
             | Edit profile
          .card-body
            .input-group.form-group
              .input-group-prepend
                span.input-group-text
                  i.fas.fa-user
              .field
                = f.input :first_name, placeholder: 'first name', label: false
            .input-group.form-group
              .input-group-prepend
                span.input-group-text
                  i.fas.fa-user
              .field
                = f.input :last_name, placeholder: 'last name', label: false
            .input-group.form-group
              .input-group-prepend
              .field
                = f.file_field :image, style: 'max-width: 256px'
                = f.error :image
            .input-group.form-group
              .input-group-prepend
                span.input-group-text
                  i.fas.fa-envelope
              .field
                = f.input :email, placeholder: 'email', label: false
      .actions
        .row
          = f.submit 'Submit', class: 'btn btn-edit'
          = link_to 'Back', user_path, class: 'btn btn-edit'
          = link_to 'Delete User',  @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-edit'

app/views/users/_group.html.slim
.col-md-6
  .card-body.p-2
    .profile-img-group.d-flex.justify-content-center
      - if group.image?
        = image_tag(group.image.show.url, alt: 'Image', class: 'profile-img')
      - else
        = image_tag('default_group.png', alt: 'Image', class: 'post-img')
    .group-name
      .d-flex.justify-content-center
        strong = group.group_name
      .d-flex.justify-content-center
        span = group.group_type

app/views/users/_user.html.slim
.row.centered-form.center-blockm.m-3
  .container
    .card-user
      .user
        .row
          .col-lg-5
            .profile-image
              - if user.image?
                = image_tag(user.image.index.url, alt: 'Image', class: 'profile-image')
              - else
                = image_tag('default_avatar.png', alt: 'Image', class: 'profile-image')
          .col-lg-7
            h4.m-t-0.m-b-0
              strong = user.full_name
            span = user.email
            .row
              = link_to 'Show', user, class: 'btn btn-user-show'

app/views/users/edit.html.slim
.jumbotron
  = render 'form', object: @user

app/views/users/groups.html.slim
- provide(:title, "#{@user.first_name} groups")
.jumbotron
  h1
    | #{@user.first_name} Groups
  .row
    - @groups.each do |group|
      = render 'groups/group', group: group
  = paginate @groups, theme: 'twitter-bootstrap-4', pagination_class: 'pagination-sm pagination-centered'

app/views/users/index.html.slim
- provide(:title, 'All users')
.jumbotron
  h1
    | All Users
  .row-user
    = render @users
  = paginate @users, theme: 'twitter-bootstrap-4', pagination_class: 'pagination-sm pagination-centered'

app/views/users/show.html.slim
- provide(:title, @user.full_name)
.jumbotron.jumbotron2
  .main-body
    .row.gutters-sm
      .col-md-4.mb-3
        .card
          .card-body
            .d-flex.flex-column.align-items-center.text-center
              .profile-image
                - if @user.image?
                  = image_tag(@user.image.show.url, alt: 'Image', class: 'profile-image')
                - else
                  = image_tag('default_avatar.png', alt: 'Image', class: 'profile-image')
              .mt-3
                h4
                  strong = @user.full_name
                span = @user.email
            .row
              = link_to 'Back', users_path, class: 'btn btn-user'
              - if current_user&.id == @user.id or current_user&.admin?
                = link_to 'Edit User', edit_user_path, class: 'btn btn-user'

        .card.mt-3.p-2[style='min-height: 339px;']
          = link_to groups_user_path, class: 'link-user-show' do
            h2.link-user-show.mb-2.mt-2
              | My Groups
          end
          .row
            = render partial: 'users/group', collection: @user.groups.limit(4), as: :group

        .card.mt-3[style='min-height: 339px;']
          h2.link-user-show.mb-2.mt-2
            | My Friends

      .col-md-8
        .card[style='min-height: 1020px;']
          = render 'posts/form', { postable: @user }
          = render partial: 'posts/post', collection: @posts, as: :post