config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'static_pages#index'
  get '/about', to: 'static_pages#about'
  resources :users do
    resources :posts, module: :users, only: %i[create destroy]
    member do
      get 'groups', to: 'users#groups', as: :groups
    end
  end
  resources :groups do
    resources :posts, module: :groups, only: %i[create destroy]
    resources :members, module: :groups, only: %i[index show create destroy] do
      delete 'remove_member', to: 'members#remove_member', as: :remove_member
    end
  end
end

app/views/layouts/_footer.html.slim
footer
  .container
    nav
      ul.nav
        li.list-inline-item
          span.text-footer
            | This is the test app created by
          a[href="https://www.linkedin.com/in/andrii-kozak-00967a175/"]
            |  Andrii Kozak.
        li.list-inline-item.ml-auto
          = link_to 'About', about_path

app/views/layouts/_header.html.slim
header
  .navbar.navbar-dark.bg-dark.navbar-inverse.fixed-top
    .container
      = link_to image_tag('rails.svg', alt: 'Rails logo'), root_path, id: 'logo'
      nav
        ul.nav.navbar-right.list-inline
          - if user_signed_in?
            li.dropdown
              a.dropdown-toggle data-toggle='dropdown' href='#'
                | Account
                b.caret
              ul.dropdown-menu.bg-dark
                li.list-inline-item
                  = link_to user_path(current_user) do
                    span.fas.fa-user-alt.fa-fw.mr-2
                    | My Profile
                    end
                li.list-inline-item
                  = link_to users_path do
                    span.fas.fa-user-friends.fa-fw.mr-2
                    | Users
                    end
                li.list-inline-item
                  = link_to groups_path do
                    span.fas.fa-users.fa-fw.mr-2
                    | Groups
                    end
            li.list-inline-item
              = link_to destroy_user_session_path, method: :delete do
                span.fas.fa-sign-out-alt.fa-fw
                | Sign out
                end
          - else
            li.list-inline-item
              = link_to new_user_registration_path do
                span.fas.fa-user-check.fa-fw.mr-1
                | Sign Up
                end
            li.list-inline-item
              = link_to new_user_session_path do
                span.fas.fa-sign-in-alt.fa-fw
                |  Login
                end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    %meta{:charset => "utf-8"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header'
    .container
      = yield
    = render 'layouts/footer'

app/views/layouts/application.html.slim
doctype transitional
html
  head
    meta[content='text/html; charset=UTF-8' http-equiv='Content-Type']
    title
      = full_title(yield(:title))
    meta[charset='utf-8']
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'iconRails.png'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        div class=("alert alert-#{key}") = value
    .container
      = yield
    = render 'layouts/footer'